### ISSUE TITLE
TableView

### ISSUE THREAD

**Issue by inceptiveKshitij** [cemolcay/SlidingContainerViewController#2]
How I add TableView on SlidingContainerViewController

**Comment by cemolcay** [comment]
just create your view controller with table view and setup SlidingContainerViewController with that view controller.

**Comment by inceptiveKshitij** [comment]
Thank you for replaying sir.
I tried that you suggested me.
But delegate method of table view not getting called.

**Comment by inceptiveKshitij** [comment]
Hi sir, 
Calling of delegate method that issue is solved. But code is getting crashed on 
"view.addSubview(slidingContainerViewController.view)" this line.

**Comment by cemolcay** [comment]
Please check out the new version, it should be fixed.
