### ISSUE TITLE
Extra swipe

### ISSUE THREAD

**Issue by arshadsk5** [cemolcay/SlidingContainerViewController#22]
I have two tab bars controllers, viewcontroller1 with index 0 & viewcontroller2 with index 1. After i reached index 1 and i am trying to swipe it more , i can see previous screens in background and once i reached the maximum index and minimum index it should not swipe any more. Please check the attachment .Please help, thanks in advance
![simulator screen shot - iphone 8 plus - 2018-07-31 at 16 06 54](https://user-images.githubusercontent.com/24600303/43454865-dfd07930-94db-11e8-99da-08a9e5f39b31.png)

**Comment by arshadsk5** [comment]
I got the solution, i was using container view for this screens. So i removed container views and added these view controllers in a uiview from code. It solved the problem

**Comment by cemolcay** [comment]
Hi, great, I'm closing this issue then?
