### ISSUE TITLE
How to add view controllers to sliding container 

### ISSUE THREAD

**Issue by swabzz** [cemolcay/SlidingContainerViewController#7]
I have 4 uiviewcontrollers in my main storyboard.
is it possible to add this for uiviewcontrollers to sliding viewcontroller

i mean i dont want to create viewcontrollers programatically.

Thanks in advance

**Comment by swabzz** [comment]
```
    //let vc1 = viewControllerWithColorAndTitle(UIColor.whiteColor(), title: "First View Controller")
  INSTED OF ABOVE LINE I AM USING

  vc1 = aViewController() [created in storyboard]
```

but cant see controlled of view controller it showing blank view controller

**Comment by cemolcay** [comment]
hi, you can instantiate view controllers in your storyboard file with `UIStoryboard`s `instantiateViewControllerWithIdentifier` method.
Just dont forget the give your view controller's `storyboard identifier` in interface builder.
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIStoryboard_Class/#//apple_ref/occ/instm/UIStoryboard/instantiateViewControllerWithIdentifier:
